services:
  db:
    image: postgres:15-alpine
    container_name: postgres_rag
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: rag_system
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rag_net

networks:
  rag_net:

volumes:
  pgdata: